name: LynxAPI
version: '${project.version}'
main: ca.lynix.lynxapi.LynxAPI
api-version: 1.15
website: lynix.ca
commands:
  clientid:
    description: Request your ClientID from our servers.
    usage: /<command>
  status:
    description: Check the Status of your connection to our servers.
    usage: /<command>